name: Flutter CI

on:
  push: 
    branches: [master]
        
jobs:
  ios:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:  
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: 'Setup Xcode 12.4'
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '12.4'

    - name: Install gpg
      run: brew install gnupg

    - name: Setup provisioning profile
      env:
        IOS_GPG_KEY_PROV: ${{ secrets.IOS_GPG_KEY_PROV }}
        IOS_GPG_KEY_P12: ${{ secrets.IOS_GPG_KEY_P12 }}
        IOS_P12_KEY: ${{ secrets.IOS_P12_KEY }}
      run: ./.github/secrets/decrypt_secrets.sh
    
    # Setup the flutter environment.
    - name: Flutter action
      uses: subosito/flutter-action@v1.4.0
      with:
        channel: 'stable' # 'dev', 'alpha', default to: 'stable'
        # flutter-version: '1.12.x' # you can also specify exact version of flutter
    
    - name: Flutter doctor
      run: flutter doctor

    # Get flutter dependencies.
    - run: flutter pub get
    
    - run: flutter pub deps -- --style=compact

    - name: Build iOS app
      run: flutter build ios --release --no-codesign --verbose

    - run: |
        xcodebuild -configuration Release \
        -workspace ios/Runner.xcworkspace \
        -scheme Runner \
        BUILD_DIR=$PWD/build/ios \
        -sdk iphoneos \
        FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO VERBOSE_SCRIPT_LOGGING=YES | xcpretty
